export const options = {
  Client: [
    { label: "Telefone", value: "phone" },
    { label: "E-mail", value: "email" },
    { label: "Endereço", value: "addressHome" },
  ],
  Customer: [
    { label: "Telefone", value: "phone" },
    { label: "Contato Principal", value: "mainContactName" },
    { label: "E-mail", value: "mainContactEmail" },
    { label: "Endereço", value: "address" },
  ],
  Department: [
    { label: "Gerente", value: "manager" },
    { label: "Membros", value: "members" },
    { label: "E-mail", value: "email" },
    { label: "Telefone", value: "phone" },
    { label: "Tipo", value: "type" },
  ],
  Group: [{ label: "Membros", value: "members" }],
  Job: [
    { label: "Cliente", value: "customer" },
    { label: "Designado", value: "worker" },
    { label: "Agendado para", value: "scheduledTo" },
    { label: "Valor", value: "price" },
    { label: "Status", value: "status" },
  ],
  Operator: [
    { label: "Nome de Operador", value: "username" },
    { label: "Perfil de Acesso", value: "role" },
    { label: "Login Realizado", value: "alreadyLogin" },
  ],
  Position: [
    { label: "Departamento", value: "department" },
    { label: "Colaboradores", value: "members" },
  ],
  Role: [{ label: "Colaboradores", value: "members" }],
  Sale: [
    { label: "Cliente", value: "customer" },
    { label: "Vendedor", value: "seller" },
    { label: "Valor", value: "price" },
    { label: "Status", value: "status" },
  ],
  Service: [
    { label: "Tipo", value: "type" },
    { label: "Departamento", value: "department" },
    { label: "Valor", value: "price" },
    { label: "Produtos", value: "products" },
  ],
  ServicePlan: [
    { label: "Período", value: "period" },
    { label: "Dia de Renovação", value: "renewDay" },
    { label: "Valor", value: "price" },
    { label: "Serviços", value: "services" },
  ],
  Stock: [
    { label: "Tipo", value: "type" },
    { label: "Membros", value: "members" },
    { label: "E-mail", value: "email" },
    { label: "Telefone", value: "phone" },
    { label: "Tipo", value: "type" },
  ],
  StockEntry: [
    { label: "Produtos", value: "items" },
    { label: "Valor", value: "price" },
    { label: "Criado por", value: "createdBy" },
    { label: "Criado em", value: "createdAt" },
    { label: "Status", value: "status" },
  ],
  User: [
    { label: "E-mail", value: "email" },
    { label: "Telefone", value: "phone" },
    { label: "Departamento", value: "department" },
    { label: "Cargo", value: "position" },
  ],
};
